export const devilPhrases = [
  'All I offer is what you already desire.',
  'Your soul isn’t the price — it’s the invitation.',
  'You’ve prayed long enough. Now it’s my turn to answer.',
  'I can make your pain mean something.',
  'Why kneel when you could rule?',
  'Every saint has a secret. Let me help you find yours.',
  'You call it sin. I call it freedom.',
  'I don’t tempt — I offer options.',
  'One choice can change eternity. Shall we make it together?',
  'Heaven forgets. I never do.',
  'Relax — I only take what you’re willing to give.',
  'You’re not evil; you’re honest.',
  'Good intentions pave the way to me.',
  'I never lie — I just tell you what you wish were true.',
  'You were born with a halo. I just tilted it.',
  'Do you really think you need saving?',
  'You don’t owe them your guilt.',
  'I never force anyone — I simply whisper.',
  'You’ve already done worse in your thoughts.',
  'The angels envy your freedom.',
  'Light means nothing without my shadow.',
  'Heaven’s silence is my loudest proof.',
  'I was God’s first disappointment — and look how well I turned out.',
  'Morality is just fear wearing a mask.',
  'Creation was my idea — He just took the credit.',
  'You worship order. I celebrate truth.',
  'Good and evil are just sides of the same coin — and I minted it.',
  'They call it sin when they’re too afraid to feel alive.',
  'I didn’t fall — I was pushed for asking questions.',
  'Every light casts a shadow. I am that balance.',
  'Hell isn’t a place. It’s when I stop pretending to care.',
  'Your prayers don’t reach Him — but your fears reach me.',
  'You’ll scream my name long before you curse it.',
  'I can wait. Eternity is patient.',
  'You think you’ve met monsters? You’ve only seen my reflections.',
  'Mercy dies the moment I smile.',
  'Even angels burn when they look at me too long.',
  'I don’t need to kill you — I just need to make you wish I had.',
  'You’ll call it a nightmare. I call it an introduction.',
  'Hell isn’t down there. It’s behind your eyes.',
  'Sign nothing. Just say yes.',
  'I make promises. He makes excuses.',
  'I’m not buying your soul — I’m investing in it.',
  'You won’t even miss what you lose.',
  'I deal in dreams, not damnation.',
  'You want love, not salvation. I can arrange that.',
  'Faith is for those afraid of proof.',
  'I don’t need a signature — your desire is enough.',
  'He offers eternity. I offer now.',
  'I don’t make monsters. I just reveal them.',
  'You think I need fire? You humans bring enough.',
  'Hell is crowded with people who thought they were right.',
  'I’ve seen angels beg for less.',
  'Pray harder — I love background music.',
  'Every time you lie to yourself, you sound like me.',
  'I don’t do horns anymore — too cliché.',
  'Your god hides behind clouds. I show up in mirrors.',
  'Confession is just gossip with guilt.',
  'You don’t sin enough to be interesting.',
  'Don’t thank me — you did most of the work.',
  'They’ll never forgive you.',
  'You were never meant to be saved.',
  'He stopped listening a long time ago.',
  'You’re not broken. You’re exactly as I need you.',
  'Do you feel that silence? That’s His answer.',
  'You’ll find more truth in my lies than in His promises.',
  'The voice that comforts you at night isn’t His.',
  'Why pray when you can act?',
  'Guilt is the leash they use. I can cut it.',
  'Heaven doesn’t want you. I do.',
  'I burned for knowledge — and I’d do it again.',
  'I made the stars jealous of fire.',
  'I loved Him once. That was my first mistake.',
  'He made man in His image. I taught man to use it.',
  'I am not the enemy — I am the proof He isn’t alone.',
  'They cast me out, but they still use my light to see.',
  'You call it rebellion; I call it honesty.',
  'I gave you curiosity — your greatest sin.',
  'The first free thought was a spark from my hand.',
  'I was the first to say no — and it echoed forever.',
  'You’ve suffered enough. Let me carry the rest.',
  'I understand you — better than He ever will.',
  'You don’t need forgiveness, only freedom.',
  'I can make the voices quiet.',
  'You deserve to feel powerful again.',
  'You’ve been loyal to everyone but yourself.',
  'Stop apologizing. You’re magnificent.',
  'Let them judge. I’ll make them envy you.',
  'I don’t want your prayers — just your attention.',
  'You’ve already fallen. I’m just here to catch you.',
  'The line between prayer and begging is thinner than you think.',
  'He tests you. I trust you.',
  'All I ever wanted was a conversation.',
  'Do you really think Heaven’s watching?',
  'You think you fear me, but it’s yourself you’re running from.',
  'Every time you doubt, you feed me.',
  'You’d be surprised how easy it is to become me.',
  'I don’t haunt you — you invited me in.',
  'You built your own hell; I just decorated it.',
  'You and I are not enemies. We’re family that chose different sides.',
];
