export const devilPhrases = [
  'I tried to sign a soul contract online but the WiFi in Hell is TERRIBLE.',
  'Your soul? Sorry, we only accept Venmo now.',
  'I`m not saying I invented taxes, but... you`re welcome.',
  'Hell`s full. We`re accepting applications for middle management positions.',
  'I fell from heaven and my back still hurts. No worker`s comp down here.',
  'Your browser history is more damning than anything I could offer.',
  'I showed up for your soul but honestly, your student loans are scarier.',
  'Heaven has harp music. We have death metal. You do the math.',
  'I can give you unlimited power! Terms and conditions apply.',
  'Sorry, can`t talk, I`m late for my hot yoga class. It`s literally just Hell.',
  'Your soul`s worth? Let me check... *googles it* ...yikes.',
  'I invented the "Reply All" button. Fear me.',
  'Fun fact: Pineapple on pizza was MY idea.',
  'I`m not the devil, I`m just misunderstood! ...Wait, no, I`m totally the devil.',
  'Your Netflix password died for your sins.',
  'I offered someone their dream job once. It was in customer service.',
  'Hell isn`t fire and brimstone anymore. It`s automated phone menus.',
  'Eternal damnation? That`s just my Spotify ads without Premium.',
  'I invented the "skip intro" button, then made it not work sometimes.',
  'Your soul AND you have to update Adobe? Tough day.',
  'Three words: Eternal. Software. Updates.',
  'I made Mondays. I`m sorry. (Not really.)',
  'Your soul contract comes with a free tote bag! ...It`s on fire.',
  'Plot twist: I`m actually just a very dedicated method actor.',
  'I didn`t create evil. I just franchised it.',
  'Hell is just a group project where you do all the work.',
  'Your eternal torture? Having to watch people eat soup loudly.',
  'I tried starting a podcast but even demons won`t listen.',
  'I invented traffic. You`re welcome for the character building.',
  'Sign here for your soul. And here. And here. Initial here...',
  'Your punishment is reading terms and conditions... FOREVER.',
  'I made auto-play videos with sound. I`m a monster.',
  'My Yelp rating for Hell is surprisingly good. 4.5 stars!',
  'Your soul is worth one used 2007 Honda Civic. Final offer.',
  'I invented the "This meeting could have been an email."',
  'Hell has WiFi but the password is on a Post-it in Heaven.',
  'Your eternal suffering? Wet socks. Forever.',
  'I`m the reason your USB never goes in the first time.',
  'Fun fact: I invented spoilers. Snape kills Dumbledore.',
  'Your soul AND you have to attend a timeshare presentation.',
  'I`m not evil, I`m just poorly socialized.',
  'Hell`s just an open-plan office with fluorescent lighting.',
  'I invented alarm clocks. Yes, I`m THAT evil.',
  'Your damnation includes mandatory team-building exercises.',
  'I tried going vegan but souls are surprisingly high in protein.',
  'Plot twist: Heaven is just Hell with better PR.',
  'I made the "close door" button in elevators not work.',
  'Your soul contract has 47 pages of fine print. Good luck!',
  'Hell is just customer service calls on hold... eternally.',
  'I invented the word "moist." Fear my power.',
  'Your torture? Stepping on LEGOs. Forever.',
  'I`m the reason your headphones get tangled in your pocket.',
  'My evil plan? Making everyone slightly uncomfortable.',
  'Hell`s dress code is business casual. Yes, FOREVER.',
  'I invented video buffering at the best part.',
  'Your soul is worth... *checks notes* ...three Dogecoin.',
  'I made autocorrect. Duck yeah!',
  'Hell is just a Zoom meeting that never ends.',
  'I invented the middle seat on airplanes.',
  'Your eternal punishment? Slow walkers in front of you.',
  'I`m the devil and even I think pumpkin spice went too far.',
  'Hell`s just watching someone type and delete "typing..."',
  'I made pennies. Completely useless torture devices.',
  'Your damnation includes mandatory icebreakers.',
  'I invented the sound of Styrofoam rubbing together.',
  'Hell`s WiFi password: "OnTheRouterDownstairs"',
  'I`m the reason your phone dies at 20%.',
  'Your torture? People who say "We need to talk" then disappear.',
  'I invented surprise baby shower invitations.',
  'Hell is just parallel parking. Forever.',
  'I made the YouTube double ads unskippable.',
  'Your soul contract includes a 30-day money-back guarantee! (Void in Hell)',
  'I`m the reason your nose gets stuffy when you lie down.',
  'Hell is just group chats you can`t leave.',
  'I invented the plot hole in your favorite show.',
  'Your eternal torture? Popcorn kernels stuck in your teeth.',
  'I`m not saying I invented Mondays, but I took credit for it.',
  'Hell is just reading recipe blogs for the actual recipe.',
  'I made websites that ask "Are you still watching?"',
  'Your damnation? Mismatched Tupperware lids.',
  'I`m the reason you can`t remember why you walked into a room.',
  'Hell is just printers that never work when you need them.',
  'I invented the feeling of forgetting someone`s name mid-conversation.',
  'Your torture? Headphone cords that catch on EVERYTHING.',
  'I made the friend who spoils movies "accidentally."',
  'Hell is just captchas. Select all the traffic lights. FOREVER.',
  'I`m the reason socks disappear in the dryer.',
  'Your eternal punishment? Songs stuck in your head at 3 AM.',
  'I invented reply-all email chains.',
  'Hell is just a never-ending software installation at 99%.',
  'I made the person who chews loudly in quiet spaces.',
  'Your damnation? Phantom phone vibrations.',
  'I`m the reason your charger cable only works at certain angles.',
  'Hell is just waiting for someone to text back. Forever.',
  'I invented the "low battery" warning that comes too late.',
  'Your torture? Hiccups that won`t stop.',
  'I made websites that scroll back to the top randomly.',
  'Hell is just mandatory fun activities at work.',
  'I`m the reason you stub your toe on furniture YOU OWN.',
  'Your eternal suffering? Slow internet when you`re in a hurry.',
  'I invented the friend request from your boss.',
  'Hell is just reading "We need to talk" with no context.',
];
